version: '3'
services:
  xweeter:
    image: xweeter:latest
    container_name: xweeter-container
    restart: always
    ports:
      - 4173:4173
    volumes:
      - xweeter-volume:/app/data
    command: npm run preview
    depends_on:
      - xweeter-api
    networks:
      - xweeter-network
  xweeter-api:
    image: xweeter-api:latest
    container_name: xweeter-api-container
    restart: always
    ports:
      - 5000:5000
    volumes:
      - xweeter-api-volume:/app/data
    command: flask run --host=0.0.0.0
    env_file:
      - xweeter-api.env
    depends_on:
      - postgres
      - minio
    networks:
      - xweeter-network
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=xweeter-db
    env_file:
      - postgres.env
    networks:
      - xweeter-network
  minio:
    image: quay.io/minio/minio
    container_name: minio-container
    restart: always
    ports:
      - 9000:9000
    networks:
      - xweeter-network
networks:
  xweeter-network:
    external: true
volumes:
  xweeter-volume:
    external: true
  xweeter-api-volume:
    external: true
  postgres-volume:
    external: true
